baseURL = "/"
title = "100daysofcode"


DefaultContentLanguage = "fr"
#DefaultContentLanguage = "en"

theme = "beautifulhugo"
metaDataFormat = "yaml"

[permalinks]
  post = "/:year/:month/:day/:title/"

pygmentsUseClasses = true
pygmentCodeFences = true
#pygmentsStyle = "friendly"
disqusShortname = "xtof"
#googleAnalytics = "XXX"

[Params]
  subtitle = "1 heure de code chaque jour pendant 100 jours"
  logo = "img/avatar-icon.png"
  ## repo Gh pour le pied de page (inclure un slash à la fin)
  ghrepo = "https://github.com/ChristopheDucamp/100daysofcode-site/"
  favicon = "img/favicon.ico"
  dateFormat = "Monday 2 January 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Revevez votre code à partir de google.com/cse. Assurez-vous d'aller sur "Look and Feel" et de modifier le Layout en "Full Width" et le Theme sur "Classic"

#PARAMS pied de page en cours

  
  ### Editez le repo de contenu (regle pour entrer automatiquement le mode "edit" ;  bien pour des liens "ameliorer cette page")
  ghdocsrepo = "https://github.com/ChristopheDucamp/100daysofcode-site/tree/master"


#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"





[Author]
  name = "xtof"
  summary ="coder 1 heure par jour pendant 100 jours. Défi personnel démarré le 24 juillet 2017."
  authorphoto ="/img/avatar-icon.jpg"
  authorurl ="page/a-propos/"
  site = "https://christopheducamp.com/"
  email = "christophe@ducamp.me"
  facebook = "christophe.ducamp"
  googleplus = "+ChristopheDucamp"
  github = "ChristopheDucamp/100daysofcode-site"
  #gitlab = "username"
  twitter = "xtof_party"
  #reddit = "username"
  linkedin = "christopheducamp"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  snapchat = "xtof_fr"
  instagram = "xtof_fr"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  spotify = "xtof_fr"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  
# MARKDOWN
## Configuration pour le parseur mardown BlackFriday : https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = true
  smartypantsQuotesNBSP = true
  latexDashes = true
  

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "À Propos"
    url = "page/a-propos/"
    weight = 3

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    weight = 2

[[menu.main]]
   parent = "notes"
    name = "Échantillon Grande Image"
    url = "2017/07/27/exemple-de-grande-image/"
    weight = 1

#[[menu.main]]
#    parent = "notes"
#    name = "Échantillon Math"
#    url = "2017/07/27/échantillon-math"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Échantillon Code"
#    url = "2017/07/27/échantillon-de-code/"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

# guillemets français


